'use strict';
let data, hidden = new Set();
const $ = id => document.getElementById(id);
const esc = s => String(s ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const names={running:'运行中',prepared:'已准备',trained:'训练完成 · 待接受',accepted:'结果已核验',interrupted:'中断 / 待续跑',failed:'失败 · 待诊断',unconfirmed:'等待状态确认'};
const colors=['#16786a','#4976bc','#c07b34','#8b61ac','#65963f','#b35a71','#408d99','#927846'];
const fmt=x=>Number(x).toPrecision(3), num=x=>Number(x).toLocaleString('en-US');
const label=r=>`${r.arm} · ${r.outer} ${r.lr.toExponential(0)}${r.objective?' · '+r.objective:''}`;
function freshness(){if(!data)return;const m=(Date.now()/1000-data.generated_at)/60;$('freshness').textContent=m>45?`快照已过期 · ${Math.floor(m)} 分钟前`:`快照年龄 ${Math.max(0,Math.floor(m))} 分钟`;$('freshness').className=m>45?'stale':'';}
function render(){
 $('updated').textContent='数据更新：'+data.generated_label;freshness();
 $('incidents').innerHTML=(data.incidents||[]).map(i=>`<details class="incident"><summary>${esc(i.title)}</summary><p>${esc(i.detail)}</p></details>`).join('');
 $('question-cards').innerHTML=data.questions.map(q=>`<article class="panel question"><span class="eyebrow">${esc(q.priority)}</span><h3>${esc(q.title)}</h3><p>${esc(q.why)}</p><p class="next">${esc(q.next)}</p></article>`).join('');
 $('pools').innerHTML=data.slots.map(s=>{let cells=[];for(const [k,n] of [['ours',s.ours],['foreign',s.other],['warm',s.warm],['unknown',s.unknown]])for(let i=0;i<(n||0);i++)cells.push(`<i class="gpu ${k}"></i>`);return `<article class="panel pool"><div class="pool-title"><strong>Pool ${esc(s.name)}</strong><span class="pool-count">${s.allocated??'未知'} 张已分配 · NEXT ${esc(s.next)}</span></div><div class="gpu-grid" role="img" aria-label="T³ ${s.ours??'未知'}，其他实验 ${s.other??'未知'}，保温 ${s.warm??'未知'}">${cells.join('')}</div><div class="pool-count">T³ <b>${s.ours??'?'}</b> · 其他实验 <b>${s.other??'?'}</b> · keep-warm <b>${s.warm??'?'}</b>${s.unknown?' · 未确认 '+s.unknown:''}</div></article>`}).join('');
 $('counts').innerHTML=Object.entries(names).map(([s,n])=>`<span class="pill">${esc(n)} ${data.runs.filter(r=>r.status===s).length}</span>`).join('');
 $('plans').innerHTML=data.plans.map(p=>{let rows=data.runs.filter(r=>r.family===p.family),running=rows.filter(r=>r.status==='running').length;return `<article class="panel plan-card"><span class="eyebrow">${esc(p.priority)}${rows.length?' · '+running+' / '+rows.length+' RUNNING':' · 结果驱动'}</span><h3>${esc(p.title)}</h3><dl><dt>为什么做</dt><dd>${esc(p.why)}</dd><dt>比较什么</dt><dd>${esc(p.design)}</dd><dt>如何决定</dt><dd>${esc(p.decision)}</dd></dl></article>`}).join('');
 $('muon-bars').innerHTML=data.accepted.muon.map((m,i)=>`<div class="gain-row"><span>${esc(m.label)}</span><div class="gain-track"><i style="width:${m.gain/.007*100}%;background:${colors[i]}"></i></div><span class="num">${m.gain.toFixed(5)}</span></div>`).join('');
 $('muon-note').textContent=data.accepted.muon_note;$('cpt-note').textContent=data.accepted.cpt_note;
 $('accepted-cpt').innerHTML=data.accepted.cpt.map(r=>`<tr><td class="num">${r.lr.toExponential(0)}</td><td class="num adverse">+${r.target.toFixed(6)}<small>[${r.target_ci.map(x=>x.toFixed(6)).join(', ')}]</small></td><td class="num adverse">+${r.forgetting.toFixed(6)}<small>[${r.forgetting_ci.map(x=>x.toFixed(6)).join(', ')}]</small></td></tr>`).join('');
 table();rates();curves();
}
function table(){const f=$('family').value,s=$('status').value,q=$('search').value.toLowerCase();let rows=data.runs.filter(r=>(f==='all'||r.family===f)&&(s==='all'||r.status===s)&&[r.id,r.model,r.domain,r.arm].join(' ').toLowerCase().includes(q));rows.sort((a,b)=>(a.status==='running'?-1:1)-(b.status==='running'?-1:1)||a.id.localeCompare(b.id));$('runs').innerHTML=rows.map(r=>`<tr><td>${esc(r.model)} / ${esc(r.domain)}<small>${r.family==='repeated17'?'多轮 CPT':r.family==='smallradius'?'Normalized 0.1×':r.family==='matchedreplay'?'同配比 replay':r.family==='directiondose'?'等位移方向／幅度':r.family==='factorial'?'主网格':'配套对照'}</small></td><td>${esc(r.arm)}<small>${esc(r.objective||'retained-mean / full-batch')}</small></td><td class="num">${esc(r.outer)} · ${r.lr.toExponential(0)}</td><td class="state ${r.status}">${names[r.status]}</td><td class="num">${num(r.step)} / ${num(r.horizon)}<div class="progress"><span style="width:${100*r.progress}%"></span></div></td><td class="num">${r.eta_hours===null?'—':'约 '+r.eta_hours.toFixed(1)+' h'}</td></tr>`).join('')||'<tr><td colspan="6" class="muted">没有符合筛选的实验。</td></tr>';}
function rates(){let old=$('curve-lr').value;const values=[...new Set(data.runs.filter(r=>r.family===$('curve-family').value&&r.domain===$('curve-domain').value).map(r=>r.lr))].sort((a,b)=>a-b);$('curve-lr').innerHTML='<option value="all">全部</option>'+values.map(x=>`<option value="${x}">${x.toExponential(0)}</option>`).join('');if(values.map(String).includes(old))$('curve-lr').value=old;}
function curves(){const f=$('curve-family').value,d=$('curve-domain').value,l=$('curve-lr').value;const all=data.runs.filter(r=>r.family===f&&r.domain===d&&(l==='all'||r.lr===Number(l)));const plotted=all.map((r,i)=>({...r,color:colors[i%colors.length],dash:i>=colors.length?'6 3':(r.arm.includes('zero')?'5 3':'')}));$('curve-legend').innerHTML=plotted.filter(r=>r.curves.length).map(r=>`<button data-run="${esc(r.id)}" aria-pressed="${!hidden.has(r.id)}"><i class="swatch" style="background:${r.color}"></i>${esc(label(r))}</button>`).join('');$('curve-legend').querySelectorAll('button').forEach(b=>b.onclick=()=>{hidden.has(b.dataset.run)?hidden.delete(b.dataset.run):hidden.add(b.dataset.run);curves()});plot('target-plot',plotted.filter(r=>!hidden.has(r.id)),'target');plot('forget-plot',plotted.filter(r=>!hidden.has(r.id)),'forgetting');}
function plot(id,runs,key){const rows=runs.filter(r=>r.curves.some(p=>p[key]!==null));if(!rows.length){$(id).innerHTML='<div class="empty">尚无该组的 development 测量</div>';return}const pts=rows.flatMap(r=>r.curves.filter(p=>p[key]!==null).map(p=>({x:p.step/r.unique_batches,y:p[key]})));let ymin=Math.min(...pts.map(p=>p.y)),ymax=Math.max(...pts.map(p=>p.y));let gap=(ymax-ymin)||.01;ymin-=gap*.12;ymax+=gap*.12;let xmax=Math.max(.01,...pts.map(p=>p.x));const w=580,h=300,left=55,right=15,top=18,bottom=40;const x=v=>left+v/xmax*(w-left-right),y=v=>h-bottom-(v-ymin)/(ymax-ymin)*(h-top-bottom);let out=`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="${key==='target'?'目标域损失':'FineWeb 遗忘'}，横轴训练轮数"><g font-family="system-ui" font-size="11" fill="var(--muted)">`;for(let i=0;i<=4;i++){let vy=ymin+(ymax-ymin)*i/4,vx=xmax*i/4;out+=`<line x1="${left}" x2="${w-right}" y1="${y(vy)}" y2="${y(vy)}" stroke="var(--line)"/><text x="${left-8}" y="${y(vy)+4}" text-anchor="end">${vy.toFixed(3)}</text><text x="${x(vx)}" y="${h-bottom+20}" text-anchor="middle">${vx.toFixed(1)}</text>`}out+=`<text x="${(w+left)/2}" y="${h-3}" text-anchor="middle">训练轮数</text></g>`;for(const r of rows){const points=r.curves.filter(p=>p[key]!==null);out+=`<polyline points="${points.map(p=>x(p.step/r.unique_batches)+','+y(p[key])).join(' ')}" fill="none" stroke="${r.color}" stroke-width="2" stroke-dasharray="${r.dash}"/>`;for(const p of points)out+=`<circle cx="${x(p.step/r.unique_batches)}" cy="${y(p[key])}" r="3.5" fill="${r.color}"><title>${esc(label(r))}\nstep ${p.step} · ${(p.step/r.unique_batches).toFixed(3)} passes\n${key}: ${p[key].toFixed(6)}</title></circle>`}out+='</svg>';$(id).innerHTML=out;}
async function load(){try{const response=await fetch('data.json?t='+Date.now(),{cache:'no-store'});if(!response.ok)throw Error(response.status);data=await response.json();render()}catch(error){$('updated').textContent='无法读取最新快照，请稍后刷新。';$('updated').className='error';console.error(error)}}
for(const id of ['family','status','search'])$(id).addEventListener('input',()=>data&&table());
for(const id of ['curve-family','curve-domain'])$(id).addEventListener('change',()=>{rates();curves()});$('curve-lr').onchange=curves;$('refresh').onclick=load;
try{const theme=localStorage.getItem('t3-theme')||(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light');document.documentElement.dataset.theme=theme}catch{}
$('theme').onclick=()=>{const t=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=t;try{localStorage.setItem('t3-theme',t)}catch{}};
load();setInterval(load,900000);setInterval(freshness,30000);
